import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';
import { readFile } from 'node:fs/promises';
// Entire report is a synthetic fixture. IPs are reserved documentation addresses;
// the fixed date does not identify any developer or user inspection.
globalThis.crypto ||= webcrypto;
const { aggregate, validateReport, safeExport, compareAddresses, normalizeIP } = await import('../web/report.js');
const item = { id: 'local.auth', status: 'PASS', required: true, observed_at: '2001-02-03T00:00:00Z', source: 'synthetic fixture', evidence_level: 'runtime', observed: { ip: '198.51.100.7' }, message: 'Synthetic fixture', remediation: '' };
const report = { schema_version: '1.0.0', tool_version: 'test', checked_at: '2001-02-03T00:00:00Z', run_location: 'local_mac', scope: { kind: 'macos' }, platform: { name: 'Darwin' }, overall: 'VERIFIED_IN_SCOPE', checks: [item], limitations: [] };
assert.equal(validateReport(report).overall, 'VERIFIED_IN_SCOPE');
assert.equal(aggregate([{ status: 'UNKNOWN', required: true }]), 'INCOMPLETE');
assert.equal(aggregate([{ status: 'SKIPPED', required: true }]), 'INCOMPLETE');
assert.equal(aggregate([{ status: 'WARN', required: true }]), 'INCOMPLETE');
assert.equal(aggregate([{ status: 'PASS', required: true }, { status: 'WARN', required: false }]), 'ISSUES_FOUND');
assert.equal(aggregate([{ status: 'FAIL', required: false }]), 'ISSUES_FOUND');
assert.equal(aggregate([]), 'INCOMPLETE');
assert.equal(validateReport({ ...report, checks: [{ ...item, status: 'UNKNOWN' }] }).overall, 'INCOMPLETE');
assert.equal(compareAddresses('198.51.100.7', '2001:db8::1'), 'DIFFERENT_FAMILY');
assert.equal(compareAddresses('2001:db8::1', '2001:0db8:0:0:0:0:0:1'), 'SAME');
assert.equal(compareAddresses('198.51.100.7', '198.51.100.8'), 'DIFFERENT');
assert.equal(compareAddresses('999.1.1.1', '198.51.100.7'), 'UNKNOWN');
assert.equal(normalizeIP('1::2::3'), null);
assert.equal(normalizeIP('1:2:3:4:5:6:7:8::'), null);
assert.equal(normalizeIP('::ffff:192.0.2.1').family, 'IPv6');
assert.equal(normalizeIP('123456::1'), null);
assert.throws(() => validateReport({ ...report, schema_version: 'future' }));
assert.throws(() => validateReport({ ...report, checks: [{ ...item, required: 'true' }] }));
assert.throws(() => validateReport({ ...report, checks: [item, item] }));
assert.throws(() => validateReport({ ...report, checks: [{ ...item, status: 'SAFE' }] }));
assert.throws(() => validateReport({ ...report, checked_at: 'not-a-date' }));
assert.throws(() => validateReport({ ...report, checks: [{ ...item, observed: { x: { x: { x: { x: { x: { x: { x: { x: 1 } } } } } } } } }] }));
assert.throws(() => validateReport('x'.repeat(1024 * 1024 + 1)));
assert.throws(() => validateReport({ ...report, checks: [{ ...item, observed: JSON.parse('{"__proto__":{"polluted":true}}') }] }));
assert.equal({}.polluted, undefined);
const malicious = validateReport({ ...report, checks: [{ ...item, message: '<img src=x onerror=alert(1)>' }] });
assert.equal(malicious.checks[0].message, '<img src=x onerror=alert(1)>');
const exported = safeExport({ ...report, checks: [{ ...item, observed: { ip: '198.51.100.7', duplicate: '198.51.100.7', ipv6: '2001:db8::1', token: 'TEST_SECRET', message: 'IP 2001:db8::1. Also [2001:db8::1] and 198.51.100.7' } }] });
const text = JSON.stringify(exported);
assert.ok(!text.includes('198.51.100.7'));
assert.ok(!text.includes('2001:db8::1'));
assert.ok(!text.includes('TEST_SECRET'));
assert.equal(exported.checks[0].observed.ip, exported.checks[0].observed.duplicate);
assert.notEqual(exported.checks[0].observed.ip, safeExport(report).checks[0].observed.ip);
const secrets = safeExport({ ...report, checks: [{ ...item, message: 'Bearer SYNTHETIC_BEARER token=SYNTHETIC_TOKEN cookie=SYNTHETIC_COOKIE email alice@example.test /Users/alice/settings https://alice:password@example.test/path?api_key=SYNTHETIC_QUERY', observed: { auth_token: 'SYNTHETIC_FIELD' } }] });
const secretText = JSON.stringify(secrets);
for (const secret of ['SYNTHETIC_BEARER', 'SYNTHETIC_TOKEN', 'SYNTHETIC_COOKIE', 'alice@example.test', '/Users/alice', 'SYNTHETIC_QUERY', 'SYNTHETIC_FIELD']) assert.ok(!secretText.includes(secret), secret);
assert.equal(secrets.checked_at, report.checked_at);
assert.equal(secrets.checks[0].observed_at, item.observed_at);
const app = await readFile(new URL('../web/app.js', import.meta.url), 'utf8');
assert.ok(!app.includes('innerHTML'));
assert.ok(!app.includes("mode: 'no-cors'"));
assert.ok(app.includes("credentials: 'omit'"));
console.log('Web report tests passed: schema, aggregate, IP families, size/depth limits, prototype rejection, redaction, safe rendering boundaries.');
